config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # CRUD Read all
  get '/tasks', to: 'tasks#index', as: :tasks

   # Create
  # One page for JUST the form
  get '/tasks/new', to: 'tasks#new', as: :new_task
  # Another action to create the instance from the form data
  post '/tasks', to: 'tasks#create'

   # Read one
   get '/tasks/:id', to: 'tasks#show', as: :task

    # Update
  # One page for JUST the form
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # Another action to update the instance from the form data
  patch '/tasks/:id', to: 'tasks#update'

   # Delete
   delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   # '/tasks'
   def index
    @tasks = Task.all
    # render 'index.html.erb'
  end

  # '/tasks/1'
  def show
    @task = Task.find(params[:id])
  end

  # '/tasks/new'
  def new
    # this instance variable is JUST for the form
    @task = Task.new
  end

  # we cant access from a URL. The form is sending the data here (/restaurants)
  # THIS DOES NOT HAVE A VIEW
  def create
    # we need to create our instance with our STRONG params
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      # show the form with the restaurant that didnt save (not a brand new one)
      render 'new', status: :unprocessable_entity
    end
  end

  # '/restaurants/1/edit'
  def edit
    # this instance variable is JUST for the form
    @task = Task.find(params[:id])
  end

  def update
    # load the the instacne i want to update
    @task = Task.find(params[:id])
    # update the instance with the strong_params
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  # we cant access this one in the URL, but a link can with a delete method
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    # we are whitelisting the attributes a user can give us
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<!-- Form builder will: -->
<!-- add the action (/restaurants) -->
<!-- add the method (post) -->
<!-- adds the authenticity token -->
<!-- grouping all of our attributes inside of one hash -->
<% @task.errors.full_messages.each do |message| %>
  <p class="text-danger"><%= task %></p>
<% end %>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
  <%= f.label :completed %>
  <%= f.check_box :completed, class: 'form-control' %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task</h1>
  <%= render 'tasks/form' %>
</div>

app/views/tasks/index.html.erb
<div class="container mt-3">
  <h1>My tasks</h1>
  <% @tasks.each do |task| %>
    <p><%= link_to task.title, task_path(task), class: 'text-decoration-none text-dark' %></p>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New Task</h1>
  <%= render 'tasks/form' %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <p><%=  @task.details %></p>
  <p>
    <%= link_to '❌', task_path(@task), data: { turbo_method: :delete, turbo_confirm: "Delete #{@task.title}?" } %>
    <%= link_to 'Tasks', tasks_path, class: 'btn btn-light'  %>
    <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-light'  %>
  </p>
</div>